// This is a BTC map(https://github.com/teambtcmap/btcmap-api/blob/master/src/rpc/generate_element_icons.rs) to lucid icons map to insure compatability

const MATERIAL_TO_LUCIDE = {
  // Default / generic
  question_mark: 'CircleHelp',
  storefront: 'Store',
  business: 'Building2',

  // Food & drink
  restaurant: 'Utensils',
  fast_food: 'Sandwich', // not returned directly, kept for completeness
  local_cafe: 'Coffee',
  coffee: 'Coffee',
  emoji_food_beverage: 'Coffee',
  local_bar: 'Beer',
  sports_bar: 'Beer',
  lunch_dining: 'Sandwich',
  bakery_dining: 'Cookie',
  tapas: 'UtensilsCrossed',
  local_pizza: 'Pizza',
  icecream: 'IceCream2',
  cake: 'Cake',
  wine_bar: 'Wine',
  liquor: 'Wine',

  // Retail / shopping
  local_grocery_store: 'ShoppingCart',
  shopping_cart: 'ShoppingCart',
  local_mall: 'ShoppingBag',
  diamond: 'Diamond',
  watch: 'Watch',
  smartphone: 'Smartphone',
  computer: 'Monitor',
  toys: 'Gamepad2',
  games: 'Gamepad2',
  videogame_asset: 'Gamepad2',
  music_note: 'Music',
  piano: 'Music',
  luggage: 'Luggage',
  checkroom: 'Shirt',
  local_florist: 'Flower',
  grass: 'Leaf',
  potted_plant: 'Flower',
  card_giftcard: 'Gift',
  menu_book: 'BookOpen',
  chair: 'Armchair',
  hardware: 'Hammer',
  local_printshop: 'Printer',
  water: 'Droplets',

  // Services
  medical_services: 'Stethoscope',
  local_pharmacy: 'Pill',
  local_hospital: 'Hospital',
  dentistry: 'Smile',
  visibility: 'Eye',
  spa: 'Flower',
  car_repair: 'Wrench',
  local_laundry_service: 'WashingMachine',
  cleaning_services: 'Sparkles',
  electrical_services: 'Zap',
  electric_bolt: 'Zap',
  plumbing: 'Wrench',
  build: 'Wrench',
  construction: 'HardHat',
  engineering: 'Cpu',
  architecture: 'PenTool',
  design_services: 'Palette',
  hvac: 'Wind',

  // Transport
  directions_car: 'Car',
  local_taxi: 'Car',
  car_rental: 'Car',
  minor_crash: 'Car',
  directions_boat: 'Ship',
  boat: 'Sailboat',
  sailing: 'Sailboat',
  pedal_bike: 'Bike',
  two_wheeler: 'Bike',
  directions_walk: 'Footprints',
  footprint: 'Footprints',
  airport_shuttle: 'Bus',
  commute: 'Train',
  local_gas_station: 'Fuel',
  flight_takeoff: 'Plane',
  panorama: 'Image',

  // Finance
  local_atm: 'Banknote',
  currency_exchange: 'ArrowLeftRight',
  account_balance: 'Landmark',
  attach_money: 'DollarSign',
  balance: 'Scale',

  // Accommodation
  hotel: 'BedDouble',
  chalet: 'Home',
  camping: 'Tent',
  home: 'Home',
  roofing: 'Home',

  // Civic / admin
  school: 'GraduationCap',
  church: 'Church',
  local_police: 'Shield',
  local_post_office: 'Mail',
  mail: 'Mail',
  museum: 'Landmark',
  local_movies: 'Film',
  palette: 'Palette',
  mic: 'Mic',
  group: 'Users',
  groups: 'Users',
  child_care: 'Baby',
  bedroom_baby: 'Baby',
  pets: 'PawPrint',
  cruelty_free: 'PawPrint',
  raven: 'Bird',

  // Leisure / sport
  fitness_center: 'Dumbbell',
  sports: 'Trophy',
  sports_score: 'Trophy',
  sports_hockey: 'Trophy',
  sports_handball: 'Trophy',
  sports_soccer: 'CircleDot',
  sports_martial_arts: 'Swords',
  golf_course: 'Flag',
  beach_access: 'Umbrella',
  park: 'TreePine',
  nature_people: 'TreePine',
  pool: 'Waves',
  surfing: 'Waves',
  kitesurfing: 'Waves',
  kayaking: 'Waves',
  water_pump: 'Waves',
  scuba_diving: 'Waves',
  paragliding: 'Wind',
  vaping_rooms: 'Wind',
  attractions: 'Star',
  casino: 'Dices',
  celebration: 'PartyPopper',
  nightlife: 'Moon',
  sauna: 'Thermometer',
  stadium: 'Building',
  factory: 'Factory',
  warehouse: 'Warehouse',
  agriculture: 'Wheat',
  cell_tower: 'Radio',
  lan: 'Network',
  dns: 'Server',
  public: 'Globe',
  tour: 'MapPin',
  translate: 'Languages',
  newspaper: 'Newspaper',
  local_parking: 'CircleParking',
  delete: 'Trash2',
  lock: 'Lock',
  science: 'FlaskConical',
  gate: 'DoorOpen',
  radar: 'Radar',
  castle: 'Castle',
  info_outline: 'Info',
  photo_camera: 'Camera',
  video: 'Video',
  videocam: 'Video',
  outdoor_grill: 'Flame',
  colorize: 'Droplet',
  water_drop: 'Droplets',
  smoking_rooms: 'Cigarette',
  adult_content: 'EyeOff',
  edit: 'Pencil',
  trip_origin: 'Circle',
  carpenter: 'Hammer',
  cooking: 'ChefHat',
  window: 'Square',
  hive: 'Hexagon',
  volunteer_activism: 'Heart',
  favorite: 'Heart',
  grid_view: 'Grid2X2',
  surgical: 'Scissors',
  imagesearch_roller: 'Paintbrush',
  wc: 'Toilet',
};

export function getBtcMapIcon(materialIconName) {
  return MATERIAL_TO_LUCIDE[materialIconName] ?? 'Store';
}
