export const sendCountryCodes = [
  {cc: '+1',   country: 'United States',                    isoCode: 'US', sms4satsId: 187},
  {cc: '+1',   country: 'Canada',                           isoCode: 'CA', sms4satsId: 36},
  {cc: '+7',   country: 'Kazakhstan',                       isoCode: 'KZ', sms4satsId: 2},
  {cc: '+7',   country: 'Russia',                           isoCode: 'RU', sms4satsId: 0},
  {cc: '+20',  country: 'Egypt',                            isoCode: 'EG', sms4satsId: 21},
  {cc: '+27',  country: 'South Africa',                     isoCode: 'ZA', sms4satsId: 31},
  {cc: '+30',  country: 'Greece',                           isoCode: 'GR', sms4satsId: 129},
  {cc: '+31',  country: 'Netherlands',                      isoCode: 'NL', sms4satsId: 48},
  {cc: '+32',  country: 'Belgium',                          isoCode: 'BE', sms4satsId: 82},
  {cc: '+33',  country: 'France',                           isoCode: 'FR', sms4satsId: 78},
  {cc: '+34',  country: 'Spain',                            isoCode: 'ES', sms4satsId: 56},
  {cc: '+36',  country: 'Hungary',                          isoCode: 'HU', sms4satsId: 84},
  {cc: '+39',  country: 'Italy',                            isoCode: 'IT', sms4satsId: 86},
  {cc: '+40',  country: 'Romania',                          isoCode: 'RO', sms4satsId: 32},
  {cc: '+41',  country: 'Switzerland',                      isoCode: 'CH', sms4satsId: 173},
  {cc: '+43',  country: 'Austria',                          isoCode: 'AT', sms4satsId: 50},
  {cc: '+44',  country: 'United Kingdom',                   isoCode: 'GB', sms4satsId: 16},
  {cc: '+46',  country: 'Sweden',                           isoCode: 'SE', sms4satsId: 46},
  {cc: '+47',  country: 'Norway',                           isoCode: 'NO', sms4satsId: 174},
  {cc: '+48',  country: 'Poland',                           isoCode: 'PL', sms4satsId: 15},
  {cc: '+49',  country: 'Germany',                          isoCode: 'DE', sms4satsId: 43},
  {cc: '+51',  country: 'Peru',                             isoCode: 'PE', sms4satsId: 65},
  {cc: '+52',  country: 'Mexico',                           isoCode: 'MX', sms4satsId: 54},
  {cc: '+54',  country: 'Argentina',                        isoCode: 'AR', sms4satsId: 39},
  {cc: '+55',  country: 'Brazil',                           isoCode: 'BR', sms4satsId: 73},
  {cc: '+56',  country: 'Chile',                            isoCode: 'CL', sms4satsId: 151},
  {cc: '+57',  country: 'Colombia',                         isoCode: 'CO', sms4satsId: 33},
  {cc: '+58',  country: 'Venezuela',                        isoCode: 'VE', sms4satsId: 70},
  {cc: '+60',  country: 'Malaysia',                         isoCode: 'MY', sms4satsId: 7},
  {cc: '+61',  country: 'Australia',                        isoCode: 'AU', sms4satsId: 175},
  {cc: '+62',  country: 'Indonesia',                        isoCode: 'ID', sms4satsId: 6},
  {cc: '+63',  country: 'Philippines',                      isoCode: 'PH', sms4satsId: 4},
  {cc: '+64',  country: 'New Zealand',                      isoCode: 'NZ', sms4satsId: 67},
  {cc: '+65',  country: 'Singapore',                        isoCode: 'SG', sms4satsId: 196},
  {cc: '+66',  country: 'Thailand',                         isoCode: 'TH', sms4satsId: 52},
  {cc: '+82',  country: 'South Korea',                      isoCode: 'KR', sms4satsId: 190},
  {cc: '+84',  country: 'Vietnam',                          isoCode: 'VN', sms4satsId: 10},
  {cc: '+86',  country: 'China',                            isoCode: 'CN', sms4satsId: 3},
  {cc: '+90',  country: 'Turkey',                           isoCode: 'TR', sms4satsId: 62},
  {cc: '+91',  country: 'India',                            isoCode: 'IN', sms4satsId: 22},
  {cc: '+92',  country: 'Pakistan',                         isoCode: 'PK', sms4satsId: 66},
  {cc: '+93',  country: 'Afghanistan',                      isoCode: 'AF', sms4satsId: 74},
  {cc: '+94',  country: 'Sri Lanka',                        isoCode: 'LK', sms4satsId: 64},
  {cc: '+95',  country: 'Myanmar',                          isoCode: 'MM', sms4satsId: 5},
  {cc: '+211', country: 'South Sudan',                      isoCode: 'SS', sms4satsId: 177},
  {cc: '+212', country: 'Morocco',                          isoCode: 'MA', sms4satsId: 37},
  {cc: '+213', country: 'Algeria',                          isoCode: 'DZ', sms4satsId: 58},
  {cc: '+216', country: 'Tunisia',                          isoCode: 'TN', sms4satsId: 89},
  {cc: '+218', country: 'Libya',                            isoCode: 'LY', sms4satsId: 102},
  {cc: '+220', country: 'Gambia',                           isoCode: 'GM', sms4satsId: 28},
  {cc: '+221', country: 'Senegal',                          isoCode: 'SN', sms4satsId: 61},
  {cc: '+222', country: 'Mauritania',                       isoCode: 'MR', sms4satsId: 114},
  {cc: '+223', country: 'Mali',                             isoCode: 'ML', sms4satsId: 69},
  {cc: '+224', country: 'Guinea',                           isoCode: 'GN', sms4satsId: 68},
  {cc: '+225', country: 'Ivory Coast',                      isoCode: 'CI', sms4satsId: 27},
  {cc: '+226', country: 'Burkina Faso',                     isoCode: 'BF', sms4satsId: 152},
  {cc: '+227', country: 'Niger',                            isoCode: 'NE', sms4satsId: 139},
  {cc: '+228', country: 'Togo',                             isoCode: 'TG', sms4satsId: 99},
  {cc: '+229', country: 'Benin',                            isoCode: 'BJ', sms4satsId: 120},
  {cc: '+230', country: 'Mauritius',                        isoCode: 'MU', sms4satsId: 157},
  {cc: '+231', country: 'Liberia',                          isoCode: 'LR', sms4satsId: 135},
  {cc: '+232', country: 'Sierra Leone',                     isoCode: 'SL', sms4satsId: 115},
  {cc: '+233', country: 'Ghana',                            isoCode: 'GH', sms4satsId: 38},
  {cc: '+234', country: 'Nigeria',                          isoCode: 'NG', sms4satsId: 19},
  {cc: '+235', country: 'Chad',                             isoCode: 'TD', sms4satsId: 42},
  {cc: '+236', country: 'Central African Republic',         isoCode: 'CF', sms4satsId: 125},
  {cc: '+237', country: 'Cameroon',                         isoCode: 'CM', sms4satsId: 41},
  {cc: '+238', country: 'Cape Verde',                       isoCode: 'CV', sms4satsId: 186},
  {cc: '+239', country: 'Sao Tome and Principe',            isoCode: 'ST', sms4satsId: 178},
  {cc: '+240', country: 'Equatorial Guinea',                isoCode: 'GQ', sms4satsId: 167},
  {cc: '+241', country: 'Gabon',                            isoCode: 'GA', sms4satsId: 154},
  {cc: '+242', country: 'Republic of the Congo',            isoCode: 'CG', sms4satsId: 150},
  {cc: '+243', country: 'Democratic Republic of the Congo', isoCode: 'CD', sms4satsId: 18},
  {cc: '+244', country: 'Angola',                           isoCode: 'AO', sms4satsId: 76},
  {cc: '+245', country: 'Guinea-Bissau',                    isoCode: 'GW', sms4satsId: 130},
  {cc: '+248', country: 'Seychelles',                       isoCode: 'SC', sms4satsId: 184},
  {cc: '+250', country: 'Rwanda',                           isoCode: 'RW', sms4satsId: 140},
  {cc: '+251', country: 'Ethiopia',                         isoCode: 'ET', sms4satsId: 71},
  {cc: '+252', country: 'Somalia',                          isoCode: 'SO', sms4satsId: 149},
  {cc: '+253', country: 'Djibouti',                         isoCode: 'DJ', sms4satsId: 168},
  {cc: '+254', country: 'Kenya',                            isoCode: 'KE', sms4satsId: 8},
  {cc: '+255', country: 'Tanzania',                         isoCode: 'TZ', sms4satsId: 9},
  {cc: '+256', country: 'Uganda',                           isoCode: 'UG', sms4satsId: 75},
  {cc: '+257', country: 'Burundi',                          isoCode: 'BI', sms4satsId: 119},
  {cc: '+258', country: 'Mozambique',                       isoCode: 'MZ', sms4satsId: 80},
  {cc: '+260', country: 'Zambia',                           isoCode: 'ZM', sms4satsId: 147},
  {cc: '+262', country: 'Reunion',                          isoCode: 'RE', sms4satsId: 146},
  {cc: '+263', country: 'Zimbabwe',                         isoCode: 'ZW', sms4satsId: 96},
  {cc: '+264', country: 'Namibia',                          isoCode: 'NA', sms4satsId: 138},
  {cc: '+265', country: 'Malawi',                           isoCode: 'MW', sms4satsId: 137},
  {cc: '+266', country: 'Lesotho',                          isoCode: 'LS', sms4satsId: 136},
  {cc: '+267', country: 'Botswana',                         isoCode: 'BW', sms4satsId: 123},
  {cc: '+268', country: 'Eswatini',                         isoCode: 'SZ', sms4satsId: 106},
  {cc: '+269', country: 'Comoros',                          isoCode: 'KM', sms4satsId: 133},
  {cc: '+291', country: 'Eritrea',                          isoCode: 'ER', sms4satsId: 176},
  {cc: '+965', country: 'Kuwait',                           isoCode: 'KW', sms4satsId: 100},
  {cc: '+966', country: 'Saudi Arabia',                     isoCode: 'SA', sms4satsId: 53},
  {cc: '+967', country: 'Yemen',                            isoCode: 'YE', sms4satsId: 30},
  {cc: '+968', country: 'Oman',                             isoCode: 'OM', sms4satsId: 107},
  {cc: '+971', country: 'United Arab Emirates',             isoCode: 'AE', sms4satsId: 95},
  {cc: '+972', country: 'Israel',                           isoCode: 'IL', sms4satsId: 13},
  {cc: '+973', country: 'Bahrain',                          isoCode: 'BH', sms4satsId: 145},
  {cc: '+974', country: 'Qatar',                            isoCode: 'QA', sms4satsId: 111},
  {cc: '+975', country: 'Bhutan',                           isoCode: 'BT', sms4satsId: 158},
  {cc: '+976', country: 'Mongolia',                         isoCode: 'MN', sms4satsId: 72},
  {cc: '+977', country: 'Nepal',                            isoCode: 'NP', sms4satsId: 81},
  {cc: '+992', country: 'Tajikistan',                       isoCode: 'TJ', sms4satsId: 143},
  {cc: '+993', country: 'Turkmenistan',                     isoCode: 'TM', sms4satsId: 161},
  {cc: '+995', country: 'Georgia',                          isoCode: 'GE', sms4satsId: 128},
  {cc: '+996', country: 'Kyrgyzstan',                       isoCode: 'KG', sms4satsId: 11},
  {cc: '+998', country: 'Uzbekistan',                       isoCode: 'UZ', sms4satsId: 40},
];
