// Constants
const TITLE_COLOR = '#083133';
const TRANSPARENT_COLOR = '#00000000';
const RAIL_BORDER_COLOR = '#073436';
const RAIL_BACKGROUND_COLOR = '#7CF3F9';
const SWIPE_SUCCESS_THRESHOLD = 95;
const DEFAULT_ANIMATION_DURATION = 400;
const RESET_AFTER_SUCCESS_DEFAULT_DELAY = 1000;
const SHOULD_ANIMATE_VIEW_ON_SUCCESS = false;

export {
  TITLE_COLOR,
  TRANSPARENT_COLOR,
  RAIL_BORDER_COLOR,
  RAIL_BACKGROUND_COLOR,
  SWIPE_SUCCESS_THRESHOLD,
  DEFAULT_ANIMATION_DURATION,
  RESET_AFTER_SUCCESS_DEFAULT_DELAY,
  SHOULD_ANIMATE_VIEW_ON_SUCCESS,
};
